Update terraform.yml

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -57,11 +57,11 @@ jobs:
           terraform fmt -check || { echo "Terraform fmt check failed for $dataset"; terraform fmt; exit 1; }
     
           echo "Planning Terraform changes for $dataset"
-          terraform plan -var-file=../../environments/${{ github.ref == 'refs/heads/main' && 'production.tfvars' || 'development.tfvars' }} || { echo "Terraform plan failed for $dataset"; exit 1; }
+          terraform plan -var-file=../environments/${{ github.ref == 'refs/heads/main' && 'production.tfvars' || 'development.tfvars' }} || { echo "Terraform plan failed for $dataset"; exit 1; }
     
           echo "Applying Terraform changes for $dataset"
-          terraform apply -var-file=../../environments/${{ github.ref == 'refs/heads/main' && 'production.tfvars' || 'development.tfvars' }} -auto-approve || { echo "Terraform apply failed for $dataset"; exit 1; }
+          terraform apply -var-file=../environments/${{ github.ref == 'refs/heads/main' && 'production.tfvars' || 'development.tfvars' }} -auto-approve || { echo "Terraform apply failed for $dataset"; exit 1; }
     
-          cd ../../
+          cd ../
         done < datasets_list.txt
 
